import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "FAQ",
    description:
        "Common questions about @pphatdev/registry: installation, supported frameworks, CLI usage, licensing, and how to browse icons.",
    alternates: { canonical: "/faq" },
    openGraph: {
        title: "FAQ | @pphatdev/registry",
        description:
            "Common questions about @pphatdev/registry: installation, supported frameworks, CLI usage, licensing, and how to browse icons.",
        type: "article",
    },
};

const faqs: { question: string; answer: string }[] = [
    {
        question: "How do I install @pphatdev/registry?",
        answer:
            "You do not need to install anything permanently. Run the CLI directly with npx: `npx pphat init` creates a pphatdev.json config in your project root. Then use `npx pphat add-icon <name>` or `npx pphat add-component <name>` to fetch what you need. If you use it often, install globally with `npm install -g @pphatdev/registry`.",
    },
    {
        question: "What frameworks does @pphatdev/registry support?",
        answer:
            "Three output formats: React / Next.js as .tsx files, Vue / Nuxt as .vue single-file components, and raw .svg for framework-agnostic use.",
    },
    {
        question: "How do I add an icon to my project?",
        answer:
            "Run `npx pphat add-icon <name>` in your project root — for example, `npx pphat add-icon react vue github`. The CLI uses the format defined in your pphatdev.json, or you can override it with `-f nextjs`, `-f nuxtjs`, or `-f svg`, and set a custom destination with `-d <path>`.",
    },
    {
        question: "How do I add a component to my project?",
        answer:
            "Run `npx pphat add-component <name>`, for example `npx pphat add-component button card modal -f nextjs -d src/components/ui`. The same -f and -d flags apply.",
    },
    {
        question: "Where do the icons and components come from?",
        answer:
            "They are fetched on demand from the public GitHub repositories pphatdev/icons and pphatdev/registry.pphat.me via raw.githubusercontent.com. There is no proprietary server or rate-limited API in the middle.",
    },
    {
        question: "Do I need an account or API key?",
        answer:
            "No. Everything is fetched from a public GitHub CDN. There are no logins, tokens, or subscriptions.",
    },
    {
        question: "What is the pphatdev.json file?",
        answer:
            "A configuration file at your project root that stores your default output format (SVG, Next.js, or Nuxt) and destination directories for icons and components. It is generated by `npx pphat init` and can be edited manually or updated with `npx pphat config`.",
    },
    {
        question: "Can I browse icons before installing?",
        answer:
            "Yes. Visit the Icon Studio at https://registry.pphat.me/icons for live search, per-icon customization (size, stroke width, color), and one-click export to SVG, React, or Vue.",
    },
    {
        question: "Is @pphatdev/registry free?",
        answer:
            "Yes. It is open source under the MIT license.",
    },
    {
        question: "Who created @pphatdev/registry?",
        answer:
            "Sophat LEAT (PPhat) — https://pphat.me. Released on 18 July 2026 under the MIT license.",
    },
];

const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "@id": "https://registry.pphat.me/faq#faqpage",
    url: "https://registry.pphat.me/faq",
    inLanguage: "en",
    isPartOf: { "@id": "https://registry.pphat.me/#website" },
    about: { "@id": "https://registry.pphat.me/#app" },
    mainEntity: faqs.map((f) => ({
        "@type": "Question",
        name: f.question,
        acceptedAnswer: {
            "@type": "Answer",
            text: f.answer,
        },
    })),
};

export default function FaqPage() {
    return (
        <main className="flex-1 w-full max-w-3xl mx-auto px-4 sm:px-6 py-12 pb-24">
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{
                    __html: JSON.stringify(faqJsonLd).replace(/</g, "\\u003c"),
                }}
            />

            <div className="flex items-center gap-2 text-xs font-mono text-muted-foreground mb-6">
                <Link href="/" className="hover:text-primary transition-colors">Home</Link>
                <span>/</span>
                <span className="text-foreground font-bold">FAQ</span>
            </div>

            <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight mb-3 text-foreground">
                Frequently Asked Questions
            </h1>
            <p className="text-muted-foreground leading-relaxed mb-10 max-w-2xl">
                Answers to common questions about installing, configuring, and using{" "}
                <span className="font-mono font-semibold text-foreground">@pphatdev/registry</span>. For deep-dive
                usage, see the{" "}
                <Link href="/docs" className="text-primary underline underline-offset-4 hover:text-primary/80">
                    documentation
                </Link>
                .
            </p>

            <div className="flex flex-col gap-6">
                {faqs.map((f, i) => (
                    <article
                        key={i}
                        className="rounded-none border border-border/60 bg-background/40 p-5 sm:p-6 backdrop-blur-sm"
                    >
                        <h2 className="text-base sm:text-lg font-bold text-foreground mb-2 leading-snug">
                            {f.question}
                        </h2>
                        <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line">
                            {f.answer}
                        </p>
                    </article>
                ))}
            </div>
        </main>
    );
}
